# 1. Python base image'ını kullanıyoruz
FROM python:3.13-slim

# 2. Çalışma dizini oluşturuluyor
WORKDIR /app

# 3. Gereksinimler dosyasını kopyalıyoruz
COPY requirements.txt /app/

# 4. Python bağımlılıklarını yüklüyoruz
RUN pip install --no-cache-dir -r requirements.txt

# 5. Flask uygulamasını kopyalıyoruz
COPY . /app

# 6. Gunicorn ile Flask uygulamasını başlatıyoruz
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:5000"]
